# Generated by Django 4.1.4 on 2023-01-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0003_account_created_at_account_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('auctionType', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auction_type',
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('constraint', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'constraint',
            },
        ),
        migrations.RenameField(
            model_name='account',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='tract',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='tract',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='tractproject',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='tractproject',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tract',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tract',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='tract',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tractproject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tractproject',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='tractproject',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='account',
            name='createdBy',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_created_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='account',
            name='deletedBy',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_deleted_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='account',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_updated_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='createdBy',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_created_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='deletedBy',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_deleted_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_updated_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='investment',
            name='createdBy',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_created_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='investment',
            name='deletedBy',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_deleted_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='investment',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_updated_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='createdBy',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_created_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='deletedBy',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_deleted_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_updated_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='tract',
            name='createdBy',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tract_created_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='tract',
            name='deletedBy',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tract_deleted_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='tract',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tract_updated_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='tractproject',
            name='createdBy',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='track_project_created_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='tractproject',
            name='deletedBy',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='track_project_deleted_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='tractproject',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='track_project_updated_by', to='eckard_api.contact'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('explanation', models.CharField(blank=True, max_length=2000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_created_by', to='eckard_api.contact')),
                ('deletedBy', models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_deleted_by', to='eckard_api.contact')),
                ('updatedBy', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_updated_by', to='eckard_api.contact')),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('offerAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eckard_api.account')),
                ('constraints', models.ManyToManyField(blank=True, to='eckard_api.constraint')),
                ('createdBy', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_created_by', to='eckard_api.contact')),
                ('deletedBy', models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_deleted_by', to='eckard_api.contact')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eckard_api.status')),
                ('updatedBy', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_updated_by', to='eckard_api.contact')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('listingType', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_type_created_by', to='eckard_api.contact')),
                ('deletedBy', models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_type_deleted_by', to='eckard_api.contact')),
                ('updatedBy', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_type_updated_by', to='eckard_api.contact')),
            ],
            options={
                'db_table': 'listing_type',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('listingName', models.CharField(max_length=100)),
                ('listingStart', models.DateTimeField()),
                ('auctionEnd', models.DateTimeField()),
                ('comments', models.CharField(max_length=2000)),
                ('nma', models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True)),
                ('minimumAsk', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('directSaleToken', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eckard_api.account')),
                ('auction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eckard_api.auctiontype')),
                ('constraints', models.ManyToManyField(blank=True, to='eckard_api.constraint')),
                ('createdBy', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_created_by', to='eckard_api.contact')),
                ('deletedBy', models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_deleted_by', to='eckard_api.contact')),
                ('listing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eckard_api.listingtype')),
                ('offer', models.ManyToManyField(related_name='offers', to='eckard_api.offer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eckard_api.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eckard_api.status')),
                ('updatedBy', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_updated_by', to='eckard_api.contact')),
            ],
            options={
                'db_table': 'listing',
            },
        ),
        migrations.AddField(
            model_name='constraint',
            name='createdBy',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constraint_created_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='deletedBy',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constraint_deleted_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constraint_updated_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='auctiontype',
            name='createdBy',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_type_created_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='auctiontype',
            name='deletedBy',
            field=models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_type_deleted_by', to='eckard_api.contact'),
        ),
        migrations.AddField(
            model_name='auctiontype',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_type_updated_by', to='eckard_api.contact'),
        ),
    ]
