# Generated by Django 4.1.4 on 2023-01-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0005_rename_deleted_at_account_deletedat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='auctiontype',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='constraint',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='listingtype',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='tract',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='tractproject',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
    ]
