# Generated by Django 4.1.4 on 2023-01-11 10:17

import django.contrib.postgres.fields.citext
from django.db import migrations, models
from django.contrib.postgres.operations import CITextExtension

class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0006_rename_is_deleted_account_isdeleted_and_more'),
    ]

    operations = [
        CITextExtension(),
        migrations.RemoveField(
            model_name='listing',
            name='directSaleToken',
        ),
        migrations.AddField(
            model_name='account',
            name='mpName',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mpStatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='buyNowPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
