# Generated by Django 4.1.4 on 2023-01-12 06:34

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    listing = apps.get_model('eckard_api', 'listing')
    for row in listing.objects.all():
        row.directSaleToken = uuid.uuid4()
        row.save(update_fields=['directSaleToken'])

class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0008_listing_directsaletoken_alter_account_createdat_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
