# Generated by Django 4.1.4 on 2023-01-12 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0009_auto_20230112_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='directSaleToken',
            field=models.UUIDField(unique=True, null=True, blank=True, default=uuid.uuid4),
        ),
    ]
