# Generated by Django 4.1.4 on 2023-01-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0010_auto_20230112_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tract',
            field=models.ManyToManyField(blank=True, through='eckard_api.TractProject', to='eckard_api.tract'),
        ),
    ]
