# Generated by Django 4.1.4 on 2023-01-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0012_remove_listing_offer_remove_tractproject_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptedOffer', models.BooleanField(blank=True, default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eckard_api.listing')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eckard_api.offer')),
            ],
            options={
                'db_table': 'listing_offer',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='offers', through='eckard_api.ListingOffer', to='eckard_api.offer'),
        ),
    ]
