# Generated by Django 4.1.4 on 2023-01-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0013_listingoffer_listing_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingoffer',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='eckard_api.listing'),
        ),
    ]
