# Generated by Django 4.1.4 on 2023-01-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0017_project_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('paidDate', models.DateField()),
                ('income', models.DecimalField(decimal_places=10, max_digits=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eckard_api.account')),
                ('createdBy', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_created_by', to='eckard_api.contact')),
                ('deletedBy', models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_deleted_by', to='eckard_api.contact')),
            ],
            options={
                'db_table': 'cash_flow',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='account',
        ),
        migrations.CreateModel(
            name='ProjectProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('gas', models.DecimalField(decimal_places=5, max_digits=12)),
                ('oil', models.DecimalField(decimal_places=5, max_digits=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('createdBy', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_production_created_by', to='eckard_api.contact')),
                ('deletedBy', models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_production_deleted_by', to='eckard_api.contact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eckard_api.project')),
                ('updatedBy', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_production_updated_by', to='eckard_api.contact')),
            ],
            options={
                'db_table': 'project_production',
            },
        ),
        migrations.CreateModel(
            name='InvestmentIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=9)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('cash_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eckard_api.cashflow')),
                ('createdBy', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_income_created_by', to='eckard_api.contact')),
                ('deletedBy', models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_income_deleted_by', to='eckard_api.contact')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eckard_api.investment')),
                ('updatedBy', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_income_updated_by', to='eckard_api.contact')),
            ],
            options={
                'db_table': 'investment_income',
            },
        ),
        migrations.AddField(
            model_name='cashflow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eckard_api.project'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='updatedBy',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_updated_by', to='eckard_api.contact'),
        ),
    ]
