# Generated by Django 4.1.4 on 2023-01-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0019_cashflow_decline_cashflow_gasprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='decline',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='gasPrice',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='noOfMonths',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='oilPrice',
        ),
    ]
