# Generated by Django 4.1.4 on 2023-01-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0021_cashcalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcalculator',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eckard_api.contact'),
        ),
    ]
