# Generated by Django 4.1.4 on 2023-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0022_cashcalculator_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='immediatePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
