# Generated by Django 4.1.4 on 2023-01-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0025_remove_offer_account_offer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingoffer',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingoffer',
            name='isDeleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
