# Generated by Django 4.1.4 on 2023-02-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0026_listingoffer_deletedat_listingoffer_isdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('value1', models.CharField(blank=True, max_length=2000, null=True)),
                ('value2', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('createdBy', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyvalue_created_by', to='eckard_api.contact')),
                ('deletedBy', models.ForeignKey(blank=True, db_column='deletedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyvalue_deleted_by', to='eckard_api.contact')),
                ('updatedBy', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyvalue_updated_by', to='eckard_api.contact')),
            ],
            options={
                'db_table': 'key_value',
            },
        ),
    ]
