# Generated by Django 4.1.4 on 2023-02-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0027_keyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='immediatePrice',
        ),
    ]
