# Generated by Django 4.1.4 on 2023-02-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0028_remove_listing_immediateprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiontype',
            name='auctionLabel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='constraint',
            name='constraintLabel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingtype',
            name='listingTypeLabel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='statusLabel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
