# Generated by Django 4.1.4 on 2023-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eckard_api', '0029_auctiontype_auctionlabel_constraint_constraintlabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='constraintType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
